import { User, Project, Proposal } from "@/types";

export const SEED_USERS: User[] = [
  // Clients
  {
    id: "client-elena",
    email: "elena@synthetix.ai",
    name: "Elena Rostova",
    role: "CLIENT",
    company: "Synthetix AI",
    headline: "Founder & CEO at Synthetix AI (YC W24)",
    bio: "Building autonomous agent infrastructure for enterprise data pipelines. Looking for world-class engineers to collaborate with.",
    skills: ["AI Strategy", "Product Architecture", "Enterprise SaaS"],
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    rating: 4.98,
    reviewCount: 32,
    verified: true,
    location: "San Francisco, CA",
    totalSpent: 184500,
    completedProjects: 14,
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "client-marcus",
    email: "marcus@apexfintech.io",
    name: "Marcus Vance",
    role: "CLIENT",
    company: "Apex Ledger Technologies",
    headline: "VP of Engineering at Apex Ledger",
    bio: "Scaling high-throughput financial settlement protocols with low latency and institutional-grade security.",
    skills: ["FinTech", "Blockchain", "High-Throughput Systems"],
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    rating: 4.92,
    reviewCount: 19,
    verified: true,
    location: "New York, NY",
    totalSpent: 96000,
    completedProjects: 8,
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "client-sophia",
    email: "sophia@novalabs.design",
    name: "Sophia Martinez",
    role: "CLIENT",
    company: "Nova Studios",
    headline: "Creative Director & Partner at Nova Studios",
    bio: "Digital product studio crafting boundary-pushing web experiences for Apple Design Award winners.",
    skills: ["Design Systems", "Brand Strategy", "Creative Direction"],
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    rating: 5.0,
    reviewCount: 26,
    verified: true,
    location: "Austin, TX",
    totalSpent: 112000,
    completedProjects: 11,
    createdAt: "2024-02-20T12:00:00Z",
  },

  // Freelancers
  {
    id: "freelancer-sarah",
    email: "sarah.chen@pulse.dev",
    name: "Sarah Chen",
    role: "FREELANCER",
    headline: "Staff AI/LLM Systems Engineer & Ex-Anthropic Contributor",
    bio: "Specializing in RAG pipelines, model quantization, LangChain, and low-latency Python/Rust microservices. Top 1% talent on PulseConnect.",
    skills: ["Python", "PyTorch", "LangChain", "OpenAI API", "Vector Databases", "Rust", "FastAPI"],
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    rating: 4.99,
    reviewCount: 47,
    hourlyRate: 140,
    verified: true,
    location: "Seattle, WA",
    totalEarned: 245000,
    completedProjects: 38,
    createdAt: "2023-11-01T09:00:00Z",
  },
  {
    id: "freelancer-liam",
    email: "liam.gallagher@pulse.dev",
    name: "Liam Gallagher",
    role: "FREELANCER",
    headline: "Principal Full-Stack Architect & Next.js Performance Specialist",
    bio: "Building zero-latency Next.js 14 applications, distributed Node.js backends, and rock-solid GraphQL APIs. Open source enthusiast.",
    skills: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "Prisma", "Tailwind CSS"],
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    rating: 5.0,
    reviewCount: 53,
    hourlyRate: 115,
    verified: true,
    location: "London, UK",
    totalEarned: 198000,
    completedProjects: 44,
    createdAt: "2023-09-15T11:00:00Z",
  },
  {
    id: "freelancer-mateo",
    email: "mateo.silva@pulse.dev",
    name: "Mateo Silva",
    role: "FREELANCER",
    headline: "Design Engineer (Figma to Production Code & Micro-Interactions)",
    bio: "Obsessed with buttery-smooth 60fps micro-interactions, dark mode aesthetics, dynamic design tokens, and Framer Motion.",
    skills: ["Figma", "UI/UX", "Tailwind CSS", "Framer Motion", "Design Systems", "Webflow"],
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    rating: 4.96,
    reviewCount: 38,
    hourlyRate: 105,
    verified: true,
    location: "Berlin, Germany",
    totalEarned: 165000,
    completedProjects: 31,
    createdAt: "2023-12-05T14:00:00Z",
  },
  {
    id: "freelancer-priya",
    email: "priya.patel@pulse.dev",
    name: "Priya Patel",
    role: "FREELANCER",
    headline: "Cloud & DevOps Architect (AWS, Kubernetes, Terraform)",
    bio: "Certified AWS Solutions Architect Pro. Automated zero-downtime CI/CD pipelines, multi-region failovers, and cost optimization.",
    skills: ["Kubernetes", "AWS", "Terraform", "Docker", "CI/CD", "Prometheus", "Golang"],
    avatarUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    rating: 4.94,
    reviewCount: 29,
    hourlyRate: 130,
    verified: true,
    location: "Toronto, Canada",
    totalEarned: 172000,
    completedProjects: 27,
    createdAt: "2024-01-20T10:00:00Z",
  }
];

export const SEED_PROJECTS: Project[] = [
  {
    id: "proj-1",
    clientId: "client-elena",
    title: "Autonomous Multi-Agent Workflow Engine for Financial Compliance",
    description: "We are seeking a senior AI Systems Engineer to build an autonomous multi-agent reasoning system that ingests SEC filings, validates cross-border transaction logs, and flags compliance anomalies. Must be experienced with LangGraph, vLLM, and low-latency embedding indexing.",
    category: "AI & Machine Learning",
    skillsRequired: ["Python", "LangChain", "Vector Databases", "FastAPI", "PyTorch"],
    budgetType: "FIXED",
    budgetMin: 8500,
    budgetMax: 14000,
    duration: "1-3 months",
    experienceLevel: "Expert",
    status: "OPEN",
    proposalsCount: 3,
    createdAt: "2024-09-12T14:30:00Z",
    updatedAt: "2024-09-12T14:30:00Z",
  },
  {
    id: "proj-2",
    clientId: "client-sophia",
    title: "Linear-Inspired Real-Time Collaboration Canvas & Design System",
    description: "Need a talented Frontend Design Engineer to build an obsidian-dark interactive collaboration canvas. Needs fluid multi-cursor awareness, undo/redo trees, keyboard shortcut managers, and zero-jank micro-animations using React and Tailwind CSS.",
    category: "UI/UX & Design",
    skillsRequired: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"],
    budgetType: "FIXED",
    budgetMin: 6000,
    budgetMax: 9500,
    duration: "Less than 1 month",
    experienceLevel: "Expert",
    status: "OPEN",
    proposalsCount: 4,
    createdAt: "2024-09-14T09:15:00Z",
    updatedAt: "2024-09-14T09:15:00Z",
  },
  {
    id: "proj-3",
    clientId: "client-marcus",
    title: "Institutional Cross-Chain Settlement Indexer & RPC Aggregator",
    description: "Apex Ledger is engineering a real-time event listener and indexer across Ethereum L2s (Arbitrum, Base, Optimism) with WebSocket stream delivery into a low-latency Redis/Postgres datastore. Experience with Go or Rust alongside Web3 RPCs is required.",
    category: "Web3 & Blockchain",
    skillsRequired: ["Rust", "PostgreSQL", "Docker", "Node.js", "WebSockets"],
    budgetType: "HOURLY",
    budgetMin: 110,
    budgetMax: 160,
    duration: "3-6 months",
    experienceLevel: "Expert",
    status: "OPEN",
    proposalsCount: 2,
    createdAt: "2024-09-15T16:45:00Z",
    updatedAt: "2024-09-15T16:45:00Z",
  },
  {
    id: "proj-4",
    clientId: "client-elena",
    title: "Distributed Kubernetes Infrastructure & Autoscaling GPU Fleet",
    description: "Looking for an experienced Cloud/DevOps Architect to deploy self-hosted H100/A100 GPU clusters on hybrid AWS and CoreWeave setups. Must implement Karpenter autoscaling, Prometheus/Grafana observability, and automated model weight checkpoint caching.",
    category: "Cloud & DevOps",
    skillsRequired: ["Kubernetes", "AWS", "Terraform", "CI/CD", "Docker"],
    budgetType: "FIXED",
    budgetMin: 12000,
    budgetMax: 18000,
    duration: "1-3 months",
    experienceLevel: "Expert",
    status: "OPEN",
    proposalsCount: 2,
    createdAt: "2024-09-16T11:20:00Z",
    updatedAt: "2024-09-16T11:20:00Z",
  },
  {
    id: "proj-5",
    clientId: "client-sophia",
    title: "High-Performance Next.js 14 Enterprise SaaS Marketing & Docs Hub",
    description: "Looking for a seasoned Next.js developer to construct our brand-new marketing platform with MDX-powered documentation, search via Algolia, dynamic OG image generation, and pristine 100/100 Core Web Vitals score.",
    category: "Full-Stack Development",
    skillsRequired: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    budgetType: "HOURLY",
    budgetMin: 85,
    budgetMax: 120,
    duration: "Less than 1 month",
    experienceLevel: "Intermediate",
    status: "OPEN",
    proposalsCount: 5,
    createdAt: "2024-09-17T08:00:00Z",
    updatedAt: "2024-09-17T08:00:00Z",
  },
  {
    id: "proj-6",
    clientId: "client-marcus",
    title: "Offline-First Cross-Platform Mobile Wallet (React Native)",
    description: "Developing a biometric-authenticated offline-first mobile companion app with encrypted SQLite storage, push notifications for settlement transactions, and clean haptic interactions.",
    category: "Mobile Apps",
    skillsRequired: ["React Native", "TypeScript", "Mobile Apps", "UI/UX"],
    budgetType: "FIXED",
    budgetMin: 9000,
    budgetMax: 15000,
    duration: "1-3 months",
    experienceLevel: "Intermediate",
    status: "IN_PROGRESS",
    proposalsCount: 6,
    createdAt: "2024-09-10T13:10:00Z",
    updatedAt: "2024-09-11T10:00:00Z",
  }
];

export const SEED_PROPOSALS: Proposal[] = [
  {
    id: "prop-1",
    projectId: "proj-1",
    freelancerId: "freelancer-sarah",
    bidAmount: 11500,
    coverLetter: "Hi Elena! I have extensive production experience building autonomous agent workflows using LangGraph and custom vLLM instances. Recently delivered a compliance verification engine for an asset manager that ingested 50,000+ SEC filings with sub-2-second retrieval. I can deliver the end-to-end prototype within 3 weeks.",
    estimatedDays: 21,
    status: "PENDING",
    createdAt: "2024-09-13T10:20:00Z",
    updatedAt: "2024-09-13T10:20:00Z",
  },
  {
    id: "prop-2",
    projectId: "proj-1",
    freelancerId: "freelancer-liam",
    bidAmount: 13200,
    coverLetter: "Hello Elena. While Sarah is an LLM specialist, my strength is pairing agent reasoning with rock-solid distributed orchestration, high-throughput queues, and resilient PostgreSQL vector schemas. Happy to discuss how we can build this with enterprise uptime guarantees.",
    estimatedDays: 28,
    status: "PENDING",
    createdAt: "2024-09-13T15:40:00Z",
    updatedAt: "2024-09-13T15:40:00Z",
  },
  {
    id: "prop-3",
    projectId: "proj-2",
    freelancerId: "freelancer-mateo",
    bidAmount: 7800,
    coverLetter: "Hi Sophia! Dark mode aesthetics and buttery 60fps micro-interactions are literally what I breathe. I have pre-built architectural blueprints for multi-cursor canvas engines and keyboard shortcut managers in Next.js + Tailwind. Let's make Nova Studios' canvas an Awwwards Site of the Day.",
    estimatedDays: 14,
    status: "PENDING",
    createdAt: "2024-09-14T11:00:00Z",
    updatedAt: "2024-09-14T11:00:00Z",
  },
  {
    id: "prop-4",
    projectId: "proj-4",
    freelancerId: "freelancer-priya",
    bidAmount: 14500,
    coverLetter: "Hi Elena! Deployed H100 clusters on hybrid CoreWeave and AWS EKS multiple times with Karpenter autoscaling and Slurm / vLLM integration. Can set up automated monitoring with Prometheus & Grafana alerting dashboards within 18 days.",
    estimatedDays: 18,
    status: "PENDING",
    createdAt: "2024-09-16T14:30:00Z",
    updatedAt: "2024-09-16T14:30:00Z",
  },
  {
    id: "prop-5",
    projectId: "proj-6",
    freelancerId: "freelancer-liam",
    bidAmount: 12500,
    coverLetter: "Marcus, I have worked on biometric-secured fintech apps and offline SQLite synchronization protocols. Ready to take this from Figma to Google Play and App Store with zero regressions.",
    estimatedDays: 35,
    status: "ACCEPTED",
    createdAt: "2024-09-10T16:00:00Z",
    updatedAt: "2024-09-11T10:00:00Z",
  }
];

export const CATEGORIES = [
  "All Categories",
  "AI & Machine Learning",
  "Full-Stack Development",
  "UI/UX & Design",
  "Cloud & DevOps",
  "Web3 & Blockchain",
  "Mobile Apps"
];

export const POPULAR_SKILLS = [
  "Next.js",
  "React",
  "TypeScript",
  "Python",
  "PyTorch",
  "LangChain",
  "Tailwind CSS",
  "Figma",
  "PostgreSQL",
  "Prisma",
  "AWS",
  "Kubernetes",
  "Docker",
  "Rust",
  "GraphQL",
  "Vector Databases"
];
